### PR TITLE
Add 2020 Christensen Invitational (B)

### PR DESCRIPTION
**Pull request by tctree333**

### CODE REVIEW

**Comment by zqianem** [comment]
School names look good. Mission Possible has a gap in placings; no team placed 17th. Do you have an official source for the results that we can compare with?

**Comment by tctree333** [comment]
I uploaded the results file to scioly.org here: https://scioly.org/wiki/index.php/File:20200201_ChristensenInvitationalResults.pdf

It looks like no team placed 17th.

**Comment by zqianem** [comment]
Sorry, pushed the wrong branch (and GitHub automatically closed the PR). Fixing now.

Edit: Could you repoen this pull request? I have proper commits but it seems like I can't push them to your fork if you don't have a pull request open.

**Comment by tctree333** [comment]
Hmm it looks like my fork is even with this repo.
I’ll just reupload the files in a new commit.

**Pull request closed without merging**
