### PR TITLE
Added NJ 2019 States results

### PR DESCRIPTION
**Pull request by CookiePie1**
I had some issues using sciolyff to validate the data, so can someone maybe please do that for me? I'm pretty sure the data is correct and in the right format, but it would be nice to do it just as a precaution. Thanks!

### CODE REVIEW

**Comment by CookiePie1** [comment]
Also, all of the netlify checks failed. Do I have to add/change other files in addition to adding the new .yaml files?

**Comment by zqianem** [comment]
Thanks for the contribution! No other files need to be added/changed except for the new YAML files.

I had to make some modifications to the files to get them to pass the ScioyFF validator. For future reference, could you review those commits to see what needed to be changed? 

Also, what were the specific issues with using the validator? I may be able to help -- the validator is an essential part of making sure the archived data is consistent and error-free.

**Comment by CookiePie1** [comment]
Thanks for the feedback! I reviewed the changes and I think I understand the things that had to be changed. 

Here's a screenshot of my command prompt: 
image

Not sure if I did anything wrong or if there's actually a problem.

**Comment by zqianem** [comment]
Oh, it looks like I used some Ruby 2.6 syntax. I'll update the gem to enforce a minimum Ruby version for now, although it may be wiser in the future for me to refactor that code to be compatible with earlier versions. You can workaround this for now by updating to the latest Ruby version.

**Pull request merged**
