### PR TITLE
 Add Christensen Invitational (by @tctree333)

### PR DESCRIPTION
**Pull request by zqianem**
Originally #26 before I messed it up.

### CODE REVIEW

**Comment by tctree333** [comment]
Hey,
Just wondering if there were any more issues that needed to be fixed for this to be merged.
Thanks

**Comment by zqianem** [comment]
Looks good, just haven't got around to merging it. Will try to find some time over the weekend to take care of this and some other site maintenance.

**Comment by tctree333** [comment]
Ah, gotcha.
Thanks!

**Comment by zqianem** [comment]
It's been a long weekend, but PR has been merged. = )

**Pull request merged**
